FROM debian:trixie

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    pkg-config \
    libnm-dev \
    libgtk-3-dev \
    libgtk-4-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src
