FROM archlinux:latest
RUN pacman -Syu --noconfirm \
    base-devel cmake extra-cmake-modules \
    plasma-workspace \
    kcoreaddons kconfig kwidgetsaddons kio ki18n kcrash kcmutils \
    networkmanager-qt modemmanager-qt \
    qt6-base qt6-svg qt6-declarative \
    vulkan-headers qtkeychain-qt6 qcoro && \
    pacman -Scc --noconfirm && \
    rm -rf /var/cache/pacman/pkg/* /tmp/*
WORKDIR /src
